window.SIDI_DATA = {
  "categories": [
    {
      "n": 1,
      "code": "151",
      "parent": "-",
      "name": "Alta Dirección",
      "order": 1,
      "status": "Activa",
      "registered": "01/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 2,
      "code": "152",
      "parent": "-",
      "name": "Estudiantes",
      "order": 2,
      "status": "Activa",
      "registered": "02/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 3,
      "code": "153",
      "parent": "-",
      "name": "Directivos y Docentes",
      "order": 3,
      "status": "Activa",
      "registered": "03/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 4,
      "code": "154",
      "parent": "-",
      "name": "Gestión Escolar",
      "order": 4,
      "status": "Activa",
      "registered": "04/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 5,
      "code": "155",
      "parent": "-",
      "name": "Recursos Educativos",
      "order": 5,
      "status": "Activa",
      "registered": "05/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 6,
      "code": "156",
      "parent": "-",
      "name": "Infraestructura Educativa",
      "order": 6,
      "status": "Inactivo",
      "registered": "06/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 7,
      "code": "157",
      "parent": "-",
      "name": "Intervenciones Minedu",
      "order": 7,
      "status": "Activa",
      "registered": "07/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 8,
      "code": "158",
      "parent": "-",
      "name": "Herramientas USE",
      "order": 8,
      "status": "Activa",
      "registered": "08/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 9,
      "code": "159",
      "parent": "-",
      "name": "Educación Superior",
      "order": 9,
      "status": "Activa",
      "registered": "09/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 10,
      "code": "160",
      "parent": "-",
      "name": "Gestión Descentralizada",
      "order": 10,
      "status": "Activa",
      "registered": "10/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 11,
      "code": "161",
      "parent": "-",
      "name": "Presupuesto e Inversiones",
      "order": 11,
      "status": "Activa",
      "registered": "11/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 12,
      "code": "162",
      "parent": "-",
      "name": "Histórico",
      "order": 12,
      "status": "Inactivo",
      "registered": "12/02/2026",
      "menuPrincipal": "-"
    },
    {
      "n": 13,
      "code": "163",
      "parent": "Reportes Power BI",
      "name": "Evaluación de Aprendizajes",
      "order": 13,
      "status": "Activa",
      "registered": "13/02/2026",
      "menuPrincipal": "Reportes Power BI"
    },
    {
      "n": 14,
      "code": "164",
      "parent": "Reportes Power BI",
      "name": "Programas Presupuestales",
      "order": 14,
      "status": "Activa",
      "registered": "14/02/2026",
      "menuPrincipal": "Reportes Power BI"
    },
    {
      "n": 15,
      "code": "165",
      "parent": "Reportes Power BI",
      "name": "Políticas Educativas",
      "order": 15,
      "status": "Activa",
      "registered": "15/02/2026",
      "menuPrincipal": "Reportes Power BI"
    },
    {
      "n": 16,
      "code": "166",
      "parent": "Reportes Power BI",
      "name": "Planeamiento Institucional",
      "order": 16,
      "status": "Activa",
      "registered": "16/02/2026",
      "menuPrincipal": "Reportes Power BI"
    },
    {
      "n": 17,
      "code": "167",
      "parent": "Reportes Power BI",
      "name": "Seguimiento Territorial",
      "order": 17,
      "status": "Activa",
      "registered": "17/02/2026",
      "menuPrincipal": "Reportes Power BI"
    },
    {
      "n": 18,
      "code": "168",
      "parent": "Reportes Power BI",
      "name": "Becas y Créditos",
      "order": 18,
      "status": "Inactivo",
      "registered": "18/02/2026",
      "menuPrincipal": "Reportes Power BI"
    },
    {
      "n": 19,
      "code": "169",
      "parent": "Reportes Power BI",
      "name": "Salud Escolar",
      "order": 19,
      "status": "Activa",
      "registered": "19/02/2026",
      "menuPrincipal": "Reportes Power BI"
    },
    {
      "n": 20,
      "code": "170",
      "parent": "Reportes Power BI",
      "name": "Innovación Educativa",
      "order": 20,
      "status": "Activa",
      "registered": "20/02/2026",
      "menuPrincipal": "Reportes Power BI"
    }
  ],
  "reports": [
    {
      "id": "brecha",
      "title": "Brecha Infraestructura (DIGIEI)",
      "category": "Alta Dirección",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "caracterizacion",
      "title": "Caracterización II.EE. (UE)",
      "category": "Alta Dirección",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "inversiones",
      "title": "Inversiones (UPI)",
      "category": "Alta Dirección",
      "group": "Infraestructura",
      "status": "active"
    },
    {
      "id": "matricula",
      "title": "Matrícula 2025-2026 - UE",
      "category": "Alta Dirección",
      "group": "Infraestructura",
      "status": "active"
    },
    {
      "id": "jeci",
      "title": "JECI",
      "category": "Estudiantes",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "matricula-2026",
      "title": "2025-2026",
      "category": "Estudiantes",
      "group": "Matrícula",
      "status": "active"
    },
    {
      "id": "plazas",
      "title": "Plazas Cubiertas",
      "category": "Directivos y Docentes",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "base",
      "title": "Base",
      "category": "Configuración del Sistema",
      "group": "Administración",
      "status": "inactive"
    },
    {
      "id": "gestion-escolar-2024",
      "title": "Gestión Escolar 2024",
      "category": "Gestión Escolar",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "gestion-escolar-indicadores",
      "title": "Indicadores de Gestión Escolar",
      "category": "Gestión Escolar",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "recursos-educativos-2024",
      "title": "Recursos Educativos 2024",
      "category": "Recursos Educativos",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "recursos-educativos-indicadores",
      "title": "Indicadores de Recursos Educativos",
      "category": "Recursos Educativos",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "infraestructura-educativa-2024",
      "title": "Infraestructura Educativa 2024",
      "category": "Infraestructura Educativa",
      "group": "Reporte directo",
      "status": "inactive"
    },
    {
      "id": "infraestructura-educativa-indicadores",
      "title": "Indicadores de Infraestructura Educativa",
      "category": "Infraestructura Educativa",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "intervenciones-minedu-2024",
      "title": "Intervenciones Minedu 2024",
      "category": "Intervenciones Minedu",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "intervenciones-minedu-indicadores",
      "title": "Indicadores de Intervenciones Minedu",
      "category": "Intervenciones Minedu",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "herramientas-use-2024",
      "title": "Herramientas USE 2024",
      "category": "Herramientas USE",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "herramientas-use-indicadores",
      "title": "Indicadores de Herramientas USE",
      "category": "Herramientas USE",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "educacion-superior-2024",
      "title": "Educación Superior 2024",
      "category": "Educación Superior",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "educacion-superior-indicadores",
      "title": "Indicadores de Educación Superior",
      "category": "Educación Superior",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "gestion-descentralizada-2024",
      "title": "Gestión Descentralizada 2024",
      "category": "Gestión Descentralizada",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "gestion-descentralizada-indicadores",
      "title": "Indicadores de Gestión Descentralizada",
      "category": "Gestión Descentralizada",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "presupuesto-e-inversiones-2024",
      "title": "Presupuesto e Inversiones 2024",
      "category": "Presupuesto e Inversiones",
      "group": "Seguimiento",
      "status": "inactive"
    },
    {
      "id": "presupuesto-e-inversiones-indicadores",
      "title": "Indicadores de Presupuesto e Inversiones",
      "category": "Presupuesto e Inversiones",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "historico-2024",
      "title": "Histórico 2024",
      "category": "Histórico",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "historico-indicadores",
      "title": "Indicadores de Histórico",
      "category": "Histórico",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "evaluacion-de-aprendizajes-2024",
      "title": "Evaluación de Aprendizajes 2024",
      "category": "Evaluación de Aprendizajes",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "evaluacion-de-aprendizajes-indicadores",
      "title": "Indicadores de Evaluación de Aprendizajes",
      "category": "Evaluación de Aprendizajes",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "programas-presupuestales-2024",
      "title": "Programas Presupuestales 2024",
      "category": "Programas Presupuestales",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "programas-presupuestales-indicadores",
      "title": "Indicadores de Programas Presupuestales",
      "category": "Programas Presupuestales",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "politicas-educativas-2024",
      "title": "Políticas Educativas 2024",
      "category": "Políticas Educativas",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "politicas-educativas-indicadores",
      "title": "Indicadores de Políticas Educativas",
      "category": "Políticas Educativas",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "planeamiento-institucional-2024",
      "title": "Planeamiento Institucional 2024",
      "category": "Planeamiento Institucional",
      "group": "Reporte directo",
      "status": "inactive"
    },
    {
      "id": "planeamiento-institucional-indicadores",
      "title": "Indicadores de Planeamiento Institucional",
      "category": "Planeamiento Institucional",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "seguimiento-territorial-2024",
      "title": "Seguimiento Territorial 2024",
      "category": "Seguimiento Territorial",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "seguimiento-territorial-indicadores",
      "title": "Indicadores de Seguimiento Territorial",
      "category": "Seguimiento Territorial",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "becas-y-creditos-2024",
      "title": "Becas y Créditos 2024",
      "category": "Becas y Créditos",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "becas-y-creditos-indicadores",
      "title": "Indicadores de Becas y Créditos",
      "category": "Becas y Créditos",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "salud-escolar-2024",
      "title": "Salud Escolar 2024",
      "category": "Salud Escolar",
      "group": "Seguimiento",
      "status": "active"
    },
    {
      "id": "salud-escolar-indicadores",
      "title": "Indicadores de Salud Escolar",
      "category": "Salud Escolar",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "innovacion-educativa-2024",
      "title": "Innovación Educativa 2024",
      "category": "Innovación Educativa",
      "group": "Reporte directo",
      "status": "active"
    },
    {
      "id": "innovacion-educativa-indicadores",
      "title": "Indicadores de Innovación Educativa",
      "category": "Innovación Educativa",
      "group": "Seguimiento",
      "status": "active"
    }
  ],
  "alerts": [
    {
      "id": 1,
      "name": "Vigencia de reporte",
      "status": "Cerrada",
      "created": "02/03/2026",
      "updated": "02/04/2026",
      "closed": "02/05/2026",
      "code": "ALR-0001",
      "description": "Controla la vigencia de publicación de reportes institucionales.",
      "desde": "02/03/2026",
      "hasta": "02/05/2026"
    },
    {
      "id": 2,
      "name": "Revisión de datos",
      "status": "Anulada",
      "created": "03/03/2026",
      "updated": "-",
      "closed": "03/05/2026",
      "code": "ALR-0002",
      "description": "Solicita revisión de datos antes de publicar la información.",
      "desde": "03/03/2026",
      "hasta": "03/05/2026"
    },
    {
      "id": 3,
      "name": "Actualización programada",
      "status": "Activa",
      "created": "04/03/2026",
      "updated": "04/04/2026",
      "closed": "-",
      "code": "ALR-0003",
      "description": "Informa una actualización programada del tablero Power BI.",
      "desde": "04/03/2026",
      "hasta": "04/05/2026"
    },
    {
      "id": 4,
      "name": "Alerta territorial",
      "status": "Cerrada",
      "created": "05/03/2026",
      "updated": "-",
      "closed": "05/05/2026",
      "code": "ALR-0004",
      "description": "Comunica una alerta territorial para seguimiento de indicadores.",
      "desde": "05/03/2026",
      "hasta": "05/05/2026"
    },
    {
      "id": 5,
      "name": "Publicación BI CAS",
      "status": "Anulada",
      "created": "06/03/2026",
      "updated": "06/04/2026",
      "closed": "06/05/2026",
      "code": "ALR-0005",
      "description": "Notifica la publicación del reporte BI CAS en el repositorio.",
      "desde": "06/03/2026",
      "hasta": "06/05/2026"
    },
    {
      "id": 6,
      "name": "Vigencia de reporte",
      "status": "Activa",
      "created": "07/03/2026",
      "updated": "-",
      "closed": "-",
      "code": "ALR-0006",
      "description": "Controla la vigencia de publicación de reportes institucionales.",
      "desde": "07/03/2026",
      "hasta": "07/05/2026"
    },
    {
      "id": 7,
      "name": "Revisión de datos",
      "status": "Cerrada",
      "created": "08/03/2026",
      "updated": "08/04/2026",
      "closed": "08/05/2026",
      "code": "ALR-0007",
      "description": "Solicita revisión de datos antes de publicar la información.",
      "desde": "08/03/2026",
      "hasta": "08/05/2026"
    },
    {
      "id": 8,
      "name": "Actualización programada",
      "status": "Anulada",
      "created": "09/03/2026",
      "updated": "-",
      "closed": "09/05/2026",
      "code": "ALR-0008",
      "description": "Informa una actualización programada del tablero Power BI.",
      "desde": "09/03/2026",
      "hasta": "09/05/2026"
    },
    {
      "id": 9,
      "name": "Alerta territorial",
      "status": "Activa",
      "created": "10/03/2026",
      "updated": "10/04/2026",
      "closed": "-",
      "code": "ALR-0009",
      "description": "Comunica una alerta territorial para seguimiento de indicadores.",
      "desde": "10/03/2026",
      "hasta": "10/05/2026"
    },
    {
      "id": 10,
      "name": "Publicación BI CAS",
      "status": "Cerrada",
      "created": "11/03/2026",
      "updated": "-",
      "closed": "11/05/2026",
      "code": "ALR-0010",
      "description": "Notifica la publicación del reporte BI CAS en el repositorio.",
      "desde": "11/03/2026",
      "hasta": "11/05/2026"
    },
    {
      "id": 11,
      "name": "Vigencia de reporte",
      "status": "Anulada",
      "created": "12/03/2026",
      "updated": "12/04/2026",
      "closed": "12/05/2026",
      "code": "ALR-0011",
      "description": "Controla la vigencia de publicación de reportes institucionales.",
      "desde": "12/03/2026",
      "hasta": "12/05/2026"
    },
    {
      "id": 12,
      "name": "Revisión de datos",
      "status": "Activa",
      "created": "13/03/2026",
      "updated": "-",
      "closed": "-",
      "code": "ALR-0012",
      "description": "Solicita revisión de datos antes de publicar la información.",
      "desde": "13/03/2026",
      "hasta": "13/05/2026"
    },
    {
      "id": 13,
      "name": "Actualización programada",
      "status": "Cerrada",
      "created": "14/03/2026",
      "updated": "14/04/2026",
      "closed": "14/05/2026",
      "code": "ALR-0013",
      "description": "Informa una actualización programada del tablero Power BI.",
      "desde": "14/03/2026",
      "hasta": "14/05/2026"
    },
    {
      "id": 14,
      "name": "Alerta territorial",
      "status": "Anulada",
      "created": "15/03/2026",
      "updated": "-",
      "closed": "15/05/2026",
      "code": "ALR-0014",
      "description": "Comunica una alerta territorial para seguimiento de indicadores.",
      "desde": "15/03/2026",
      "hasta": "15/05/2026"
    },
    {
      "id": 15,
      "name": "Publicación BI CAS",
      "status": "Activa",
      "created": "16/03/2026",
      "updated": "16/04/2026",
      "closed": "-",
      "code": "ALR-0015",
      "description": "Notifica la publicación del reporte BI CAS en el repositorio.",
      "desde": "16/03/2026",
      "hasta": "16/05/2026"
    },
    {
      "id": 16,
      "name": "Vigencia de reporte",
      "status": "Cerrada",
      "created": "17/03/2026",
      "updated": "-",
      "closed": "17/05/2026",
      "code": "ALR-0016",
      "description": "Controla la vigencia de publicación de reportes institucionales.",
      "desde": "17/03/2026",
      "hasta": "17/05/2026"
    },
    {
      "id": 17,
      "name": "Revisión de datos",
      "status": "Anulada",
      "created": "18/03/2026",
      "updated": "18/04/2026",
      "closed": "18/05/2026",
      "code": "ALR-0017",
      "description": "Solicita revisión de datos antes de publicar la información.",
      "desde": "18/03/2026",
      "hasta": "18/05/2026"
    },
    {
      "id": 18,
      "name": "Actualización programada",
      "status": "Activa",
      "created": "19/03/2026",
      "updated": "-",
      "closed": "-",
      "code": "ALR-0018",
      "description": "Informa una actualización programada del tablero Power BI.",
      "desde": "19/03/2026",
      "hasta": "19/05/2026"
    },
    {
      "id": 19,
      "name": "Alerta territorial",
      "status": "Cerrada",
      "created": "20/03/2026",
      "updated": "20/04/2026",
      "closed": "20/05/2026",
      "code": "ALR-0019",
      "description": "Comunica una alerta territorial para seguimiento de indicadores.",
      "desde": "20/03/2026",
      "hasta": "20/05/2026"
    },
    {
      "id": 20,
      "name": "Publicación BI CAS",
      "status": "Anulada",
      "created": "21/03/2026",
      "updated": "-",
      "closed": "21/05/2026",
      "code": "ALR-0020",
      "description": "Notifica la publicación del reporte BI CAS en el repositorio.",
      "desde": "21/03/2026",
      "hasta": "21/05/2026"
    },
    {
      "id": 21,
      "name": "Vigencia de reporte",
      "status": "Activa",
      "created": "22/03/2026",
      "updated": "22/04/2026",
      "closed": "-",
      "code": "ALR-0021",
      "description": "Controla la vigencia de publicación de reportes institucionales.",
      "desde": "22/03/2026",
      "hasta": "22/05/2026"
    },
    {
      "id": 22,
      "name": "Revisión de datos",
      "status": "Cerrada",
      "created": "23/03/2026",
      "updated": "-",
      "closed": "23/05/2026",
      "code": "ALR-0022",
      "description": "Solicita revisión de datos antes de publicar la información.",
      "desde": "23/03/2026",
      "hasta": "23/05/2026"
    },
    {
      "id": 23,
      "name": "Actualización programada",
      "status": "Anulada",
      "created": "24/03/2026",
      "updated": "24/04/2026",
      "closed": "24/05/2026",
      "code": "ALR-0023",
      "description": "Informa una actualización programada del tablero Power BI.",
      "desde": "24/03/2026",
      "hasta": "24/05/2026"
    },
    {
      "id": 24,
      "name": "Alerta territorial",
      "status": "Activa",
      "created": "25/03/2026",
      "updated": "-",
      "closed": "-",
      "code": "ALR-0024",
      "description": "Comunica una alerta territorial para seguimiento de indicadores.",
      "desde": "25/03/2026",
      "hasta": "25/05/2026"
    },
    {
      "id": 25,
      "name": "Publicación BI CAS",
      "status": "Cerrada",
      "created": "26/03/2026",
      "updated": "26/04/2026",
      "closed": "26/05/2026",
      "code": "ALR-0025",
      "description": "Notifica la publicación del reporte BI CAS en el repositorio.",
      "desde": "26/03/2026",
      "hasta": "26/05/2026"
    }
  ],
  "submenus": [
    {
      "n": 1,
      "code": "10505001",
      "menu": "Alta Dirección",
      "submenu": "Brecha Infraestructura (DIGIEI)",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "01/03/2026",
      "order": 1,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505001"
    },
    {
      "n": 2,
      "code": "10505002",
      "menu": "Alta Dirección",
      "submenu": "Caracterización II.EE. (UE)",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "02/03/2026",
      "order": 2,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505002"
    },
    {
      "n": 3,
      "code": "10505003",
      "menu": "Alta Dirección",
      "submenu": "Inversiones (UPI)",
      "group": "Infraestructura",
      "status": "Activa",
      "registered": "03/03/2026",
      "order": 3,
      "hasDependency": true,
      "parent": "Alta Dirección",
      "category": "Infraestructura",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505003"
    },
    {
      "n": 4,
      "code": "10505004",
      "menu": "Alta Dirección",
      "submenu": "Matrícula 2025-2026 - UE",
      "group": "Infraestructura",
      "status": "Activa",
      "registered": "04/03/2026",
      "order": 4,
      "hasDependency": true,
      "parent": "Alta Dirección",
      "category": "Infraestructura",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505004"
    },
    {
      "n": 5,
      "code": "10505005",
      "menu": "Estudiantes",
      "submenu": "JECI",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "05/03/2026",
      "order": 5,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505005"
    },
    {
      "n": 6,
      "code": "10505006",
      "menu": "Estudiantes",
      "submenu": "2025-2026",
      "group": "Matrícula",
      "status": "Activa",
      "registered": "06/03/2026",
      "order": 6,
      "hasDependency": true,
      "parent": "Estudiantes",
      "category": "Matrícula",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505006"
    },
    {
      "n": 7,
      "code": "10505007",
      "menu": "Directivos y Docentes",
      "submenu": "Plazas Cubiertas",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "07/03/2026",
      "order": 7,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505007"
    },
    {
      "n": 8,
      "code": "10505008",
      "menu": "Configuración del Sistema",
      "submenu": "Base",
      "group": "Administración",
      "status": "Inactivo",
      "registered": "08/03/2026",
      "order": 8,
      "hasDependency": true,
      "parent": "Configuración del Sistema",
      "category": "Administración",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505008"
    },
    {
      "n": 9,
      "code": "10505009",
      "menu": "Gestión Escolar",
      "submenu": "Gestión Escolar 2024",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "09/03/2026",
      "order": 9,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505009"
    },
    {
      "n": 10,
      "code": "10505010",
      "menu": "Gestión Escolar",
      "submenu": "Indicadores de Gestión Escolar",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "10/03/2026",
      "order": 1,
      "hasDependency": true,
      "parent": "Gestión Escolar",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505010"
    },
    {
      "n": 11,
      "code": "10505011",
      "menu": "Recursos Educativos",
      "submenu": "Recursos Educativos 2024",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "11/03/2026",
      "order": 2,
      "hasDependency": true,
      "parent": "Recursos Educativos",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505011"
    },
    {
      "n": 12,
      "code": "10505012",
      "menu": "Recursos Educativos",
      "submenu": "Indicadores de Recursos Educativos",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "12/03/2026",
      "order": 3,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505012"
    },
    {
      "n": 13,
      "code": "10505013",
      "menu": "Infraestructura Educativa",
      "submenu": "Infraestructura Educativa 2024",
      "group": "Reporte directo",
      "status": "Inactivo",
      "registered": "13/03/2026",
      "order": 4,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505013"
    },
    {
      "n": 14,
      "code": "10505014",
      "menu": "Infraestructura Educativa",
      "submenu": "Indicadores de Infraestructura Educativa",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "14/03/2026",
      "order": 5,
      "hasDependency": true,
      "parent": "Infraestructura Educativa",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505014"
    },
    {
      "n": 15,
      "code": "10505015",
      "menu": "Intervenciones Minedu",
      "submenu": "Intervenciones Minedu 2024",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "15/03/2026",
      "order": 6,
      "hasDependency": true,
      "parent": "Intervenciones Minedu",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505015"
    },
    {
      "n": 16,
      "code": "10505016",
      "menu": "Intervenciones Minedu",
      "submenu": "Indicadores de Intervenciones Minedu",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "16/03/2026",
      "order": 7,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505016"
    },
    {
      "n": 17,
      "code": "10505017",
      "menu": "Herramientas USE",
      "submenu": "Herramientas USE 2024",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "17/03/2026",
      "order": 8,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505017"
    },
    {
      "n": 18,
      "code": "10505018",
      "menu": "Herramientas USE",
      "submenu": "Indicadores de Herramientas USE",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "18/03/2026",
      "order": 9,
      "hasDependency": true,
      "parent": "Herramientas USE",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505018"
    },
    {
      "n": 19,
      "code": "10505019",
      "menu": "Educación Superior",
      "submenu": "Educación Superior 2024",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "19/03/2026",
      "order": 1,
      "hasDependency": true,
      "parent": "Educación Superior",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505019"
    },
    {
      "n": 20,
      "code": "10505020",
      "menu": "Educación Superior",
      "submenu": "Indicadores de Educación Superior",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "20/03/2026",
      "order": 2,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505020"
    },
    {
      "n": 21,
      "code": "10505021",
      "menu": "Gestión Descentralizada",
      "submenu": "Gestión Descentralizada 2024",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "21/03/2026",
      "order": 3,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505021"
    },
    {
      "n": 22,
      "code": "10505022",
      "menu": "Gestión Descentralizada",
      "submenu": "Indicadores de Gestión Descentralizada",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "22/03/2026",
      "order": 4,
      "hasDependency": true,
      "parent": "Gestión Descentralizada",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505022"
    },
    {
      "n": 23,
      "code": "10505023",
      "menu": "Presupuesto e Inversiones",
      "submenu": "Presupuesto e Inversiones 2024",
      "group": "Seguimiento",
      "status": "Inactivo",
      "registered": "23/03/2026",
      "order": 5,
      "hasDependency": true,
      "parent": "Presupuesto e Inversiones",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505023"
    },
    {
      "n": 24,
      "code": "10505024",
      "menu": "Presupuesto e Inversiones",
      "submenu": "Indicadores de Presupuesto e Inversiones",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "24/03/2026",
      "order": 6,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505024"
    },
    {
      "n": 25,
      "code": "10505025",
      "menu": "Histórico",
      "submenu": "Histórico 2024",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "25/03/2026",
      "order": 7,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505025"
    },
    {
      "n": 26,
      "code": "10505026",
      "menu": "Histórico",
      "submenu": "Indicadores de Histórico",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "26/03/2026",
      "order": 8,
      "hasDependency": true,
      "parent": "Histórico",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505026"
    },
    {
      "n": 27,
      "code": "10505027",
      "menu": "Evaluación de Aprendizajes",
      "submenu": "Evaluación de Aprendizajes 2024",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "01/03/2026",
      "order": 9,
      "hasDependency": true,
      "parent": "Evaluación de Aprendizajes",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505027"
    },
    {
      "n": 28,
      "code": "10505028",
      "menu": "Evaluación de Aprendizajes",
      "submenu": "Indicadores de Evaluación de Aprendizajes",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "02/03/2026",
      "order": 1,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505028"
    },
    {
      "n": 29,
      "code": "10505029",
      "menu": "Programas Presupuestales",
      "submenu": "Programas Presupuestales 2024",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "03/03/2026",
      "order": 2,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505029"
    },
    {
      "n": 30,
      "code": "10505030",
      "menu": "Programas Presupuestales",
      "submenu": "Indicadores de Programas Presupuestales",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "04/03/2026",
      "order": 3,
      "hasDependency": true,
      "parent": "Programas Presupuestales",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505030"
    },
    {
      "n": 31,
      "code": "10505031",
      "menu": "Políticas Educativas",
      "submenu": "Políticas Educativas 2024",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "05/03/2026",
      "order": 4,
      "hasDependency": true,
      "parent": "Políticas Educativas",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505031"
    },
    {
      "n": 32,
      "code": "10505032",
      "menu": "Políticas Educativas",
      "submenu": "Indicadores de Políticas Educativas",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "06/03/2026",
      "order": 5,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505032"
    },
    {
      "n": 33,
      "code": "10505033",
      "menu": "Planeamiento Institucional",
      "submenu": "Planeamiento Institucional 2024",
      "group": "Reporte directo",
      "status": "Inactivo",
      "registered": "07/03/2026",
      "order": 6,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505033"
    },
    {
      "n": 34,
      "code": "10505034",
      "menu": "Planeamiento Institucional",
      "submenu": "Indicadores de Planeamiento Institucional",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "08/03/2026",
      "order": 7,
      "hasDependency": true,
      "parent": "Planeamiento Institucional",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505034"
    },
    {
      "n": 35,
      "code": "10505035",
      "menu": "Seguimiento Territorial",
      "submenu": "Seguimiento Territorial 2024",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "09/03/2026",
      "order": 8,
      "hasDependency": true,
      "parent": "Seguimiento Territorial",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505035"
    },
    {
      "n": 36,
      "code": "10505036",
      "menu": "Seguimiento Territorial",
      "submenu": "Indicadores de Seguimiento Territorial",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "10/03/2026",
      "order": 9,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505036"
    },
    {
      "n": 37,
      "code": "10505037",
      "menu": "Becas y Créditos",
      "submenu": "Becas y Créditos 2024",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "11/03/2026",
      "order": 1,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505037"
    },
    {
      "n": 38,
      "code": "10505038",
      "menu": "Becas y Créditos",
      "submenu": "Indicadores de Becas y Créditos",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "12/03/2026",
      "order": 2,
      "hasDependency": true,
      "parent": "Becas y Créditos",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505038"
    },
    {
      "n": 39,
      "code": "10505039",
      "menu": "Salud Escolar",
      "submenu": "Salud Escolar 2024",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "13/03/2026",
      "order": 3,
      "hasDependency": true,
      "parent": "Salud Escolar",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505039"
    },
    {
      "n": 40,
      "code": "10505040",
      "menu": "Salud Escolar",
      "submenu": "Indicadores de Salud Escolar",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "14/03/2026",
      "order": 4,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505040"
    },
    {
      "n": 41,
      "code": "10505041",
      "menu": "Innovación Educativa",
      "submenu": "Innovación Educativa 2024",
      "group": "Reporte directo",
      "status": "Activa",
      "registered": "15/03/2026",
      "order": 5,
      "hasDependency": false,
      "parent": "-",
      "category": "Reporte directo",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505041"
    },
    {
      "n": 42,
      "code": "10505042",
      "menu": "Innovación Educativa",
      "submenu": "Indicadores de Innovación Educativa",
      "group": "Seguimiento",
      "status": "Activa",
      "registered": "16/03/2026",
      "order": 6,
      "hasDependency": true,
      "parent": "Innovación Educativa",
      "category": "Seguimiento",
      "form": "Power BI",
      "url": "https://app.powerbi.com/view?r=demo-10505042"
    }
  ],
  "user": {
    "name": "Usuario Demo",
    "role": "Administrador",
    "email": "demo@minedu.gob.pe"
  },
  "notifications": [
    {
      "title": "Nueva alerta publicada",
      "meta": "Hace 5 min",
      "href": "alertas.html"
    },
    {
      "title": "Reporte actualizado",
      "meta": "Hoy",
      "href": "visor-bi.html?reporte=brecha"
    },
    {
      "title": "Alerta anulada",
      "meta": "Ayer",
      "href": "alertas.html"
    }
  ],
  "roles": [
    {
      "n": 1,
      "id": 157,
      "code": "GSIDI_01",
      "name": "Administrador del Sistema",
      "checked": true
    },
    {
      "n": 2,
      "id": 186,
      "code": "GSIDI_02",
      "name": "Administrador",
      "checked": true
    },
    {
      "n": 3,
      "id": 187,
      "code": "GSIDI_03",
      "name": "Minedu",
      "checked": true
    },
    {
      "n": 4,
      "id": 188,
      "code": "GSIDI_04",
      "name": "Alta Dirección",
      "checked": true
    },
    {
      "n": 5,
      "id": 189,
      "code": "GSIDI_05",
      "name": "DRE - GRE",
      "checked": true
    },
    {
      "n": 6,
      "id": 190,
      "code": "GSIDI_06",
      "name": "UGEL",
      "checked": false
    },
    {
      "n": 7,
      "id": 191,
      "code": "GSIDI_07",
      "name": "Visitantes",
      "checked": false
    },
    {
      "n": 8,
      "id": 192,
      "code": "GSIDI_08",
      "name": "Especialista",
      "checked": false
    }
  ]
};
